#+HTML: <div align="center">
* OEC: Opinionated Emacs Configuration
#+HTML: </div>

* Overview
This is my personal =GNU/Emacs= config. I am currently running =Emacs= on
Windows, but it works on =Linux= as well. I am using =GNU/Emacs 29.0.50=
and it works without any problems. With lower versions, there may be
some problems. But I can't pinpoint the problems, because they are
absolutely random and may be host dependant.

This config is maintained and will get updated in the future. There
could be some major changes with one commit.

I use this config mostly for org-mode and programming. For
programming, I use =LSP= and =Tree-sitter=.

* Installation
First you have to clone this repository. Before starting this config
for the first time, you must setup the config. These are interactive
script is called via make:

#+begin_src sh
make install
#+end_src

All the information that is stored in the home directory in the
=.oec.el= file.

If you are on windows, the config may error the first time. This is
because emacs open more files than windows allows. If this happens,
just restart emacs a few times and after 2-3 restarts, everything
should be fine.

I use a =planck ez= keyboard and that keyboard does not have dedicated
number keys. On installation, you have to answer if you use a very
small keyboard. If =t= there will be some rebinds of common keybinds.

Before starting emacs, I recommend to install =MSYS2= to easily manage
external dependencies. Install it to =C:\msys64=. Then add
=C:\msys64\mingw64\bin\= to the =PATH=.

* Customization
The config itself is designed to activate and deactivate certain
modules. The loaded modules are defined in the =.oec.el= file. If a
module should be deactivated, you have to add two semicolons at the
beginning of the line and restart emacs.

Currently two completion frameworks are configured. By default =helm= is
used. But if you like the collection of packages around =ivy= more, you
just have to comment the line where helm is defined and uncomment the
ivy line.

* Update
To update and get the newest config, you just have to pull it from
github by calling:

#+begin_src sh
git pull origin master
#+end_src
