#+Title: eMax - Personal Emacs Config
#+Author: Dominik Keller
#+OPTIONS: toc:t date:nil
#+EXPORT_FILE_NAME: README
#+LATEX_CLASS: modern
#+LANGUAGE: en

* Overview
This is my personal =GNU Emacs= config. I use =GNU Emacs= for the most
time on =Microsoft Windows 10=. I am using =GNU Emacs 27.1= and it works
without any problems. I want to upgrade to =GCCEmacs=, but I can't
compile my config correctly.

This config is maintained and will get updated in the future. There
could be some major changes with one commit, because of a really
boring lesson.

I use this config mostly for =org-mode= and programming. For
programming, I use =LSP=, but hardly anything else.

* Installation (Windows)
Install =GNU Emacs= from the official [[https://www.gnu.org/software/emacs/download.html][mirror]]. Preferably install the
latest Release: version =27.1=. Before starting =GNU Emacs=, install
[[https://www.msys2.org/][MSYS2]] to easily manage external dependencies. Install it to =C:\msys64=.
Then add =C:\msys64\mingw64\bin\= to the =PATH=. 

First install =Git=, =aspell=:

#+begin_src shell
  $ pacman -S git
  $ pacman -S mingw-w64-x86_64-sqlite3
  $ pacman -S mingw-w64-x86_64-aspell
  $ pacman -S mingw-w64-x86_64-aspell-de
  $ pacman -S mingw-w64-x86_64-python
  $ pip install python-language-server[all]
  $ pip install pyls-black pyls-isort pyls-mypy
#+end_src

Unfortunately, you have to install some dependencies from the
internet:
- install the [[https://sourcefoundry.org/hack/][Hack]] font.
- Install [[MiKTeX]] to export =org-mode= to =LaTeX= -> =PDF=
- install [[https://rustup.rs/][Rust]]
  - install Rust linter [[https://github.com/rust-lang/rust-clippy][Clippy]]
    - environment variables are set automatically
  - change compiler with: =rustup set default-host
    x86_64-pc-windows-gnu=
  - install [[https://github.com/rust-analyzer/rust-analyzer/releases/tag][rust analyzer]]
    - either copy =rust-analyzer-windows.exe= to
      =C:\Users\USERNAME\.cargo\bin= or set additional environment
      variable.
    - rename file to =rust-analyzer.exe=
- autocomplete c headers wants to know where the header files are.
      
Then get my config with =Git=. On Windows, the config resides in the
directory =C:\Users\USER\AppData\Roaming\=.

#+begin_src emacs-lisp
  $ cd C:\Users\USER\AppData\Roaming\
  $ mkdir .emacs.d
  $ cd .emacs.d
  $ git init
  $ git remote add origin https://www.github.com/domse007/.emacs.d/
  $ git pull origin master
#+end_src

After that you can open =GNU Emacs=. It will automatically install all
packages and byte-compile them.

But you still have to modify some variables. Open the file =init.el=.
Look for the function =user-change-base-path=. Then modify the the
function, that it looks like this:

#+begin_src emacs-lisp
  (defun user-change-base-path ()
    (when (string-equal user-system-name "SYSTEM_NAME")
      (setq user-system-base-path "DESIRED_LOCATION")))
#+end_src

Replace =SYSTEM_NAME= with the name of your system. Then choose a
folder, where you want to store all your files.

** Update
If you want to get the newest commit, open the terminal and change to
the =.emacs.d= directory.

#+begin_src shell
  $ git pull origin master
#+end_src
