#+HTML: <div align="center">
* OEC: Opinionated Emacs Configuration
#+HTML: </div>

* Overview
This is my personal =GNU/Emacs= config. I am currently running =Emacs= on
Windows, but it works on =Linux= as well. I am using =GNU/Emacs 29.0.50=
and it works without any problems. With lower versions, there may be
some problems. But I can't pinpoint the problems, because they are
absolutely random and may be host dependant.

This config is maintained and will get updated in the future. There
could be some major changes with one commit.

I use this config mostly for org-mode and programming. For
programming, I use =LSP= and =Tree-sitter=.

* Installation
First you have to clone this repository. After the first start, you
must set machine specific settings. These are stored in the
=~/.emacs-customs.el= file. The file can be created by calling =M-x
dk/install-customs-file=. It writes the currently applied variables.

If you are on windows, the config may error the first time. This is
because emacs open more files than windows allows. If this happens,
just restart emacs a few times and after 2-3 restarts, everything
should be fine.

I use a =planck ez= keyboard and that keyboard does not have dedicated
number keys. On installation, you have to answer if you use a very
small keyboard. If =t= there will be some rebinds of common keybinds.

Before starting emacs, I recommend to install =MSYS2= to easily manage
external dependencies. Install it to =C:\msys64=. Then add
=C:\msys64\mingw64\bin\= to the =PATH=.

* Update
To update and get the newest config, you just have to pull it from
github by calling:

#+begin_src sh
git pull origin master
#+end_src
