#+HTML: <div align="center">
* =Emacs Configuration=
#+HTML: </div>

* Overview
This is my personal =GNU/Emacs= config. I am currently running =Emacs= on
Windows, but it works on =Linux= as well. I am using =GNU/Emacs 29.0.50=
and it works without any problems. With lower versions, there may be
some problems. But I can't pinpoint the problems, because they are
absolutely random and may be host dependant.

This config is maintained and will get updated in the future. There
could be some major changes with one commit.

I use this config mostly for org-mode and programming. For
programming, I use =LSP= and =Tree-sitter=.

* Installation
First clone this repository and install all the system dependencies
(installation steps below). On the first startup, emacs will prompt
you to set some default directories. They will be saved in the file
=.emacs-config-vars= and are stored in your home directory. If you ever
want to change the paths, you can do this by interactively calling
=dk/reset-config-variables=. This functionality resides in the file
=~/.emacs.d/modules/custom-set-variables.el= and can be tweaked there a
bit. 

If you install this configuration for the first time, it could throw
some errors. If this happens, just restart emacs a few times and after
2-3 restarts, everything should be fine.

** Manjaro
The installation on Linux is very simple. Just execute the following
command:

#+begin_src sh
$ sudo make
#+end_src

** Windows 10
Install =GNU/Emacs= from the official mirror. Preferably install the
latest Release: version 27.1. Alternatively, you can use the official
Microsoft package manager: =winget=. Please run the Makefile with admin privilege.

#+begin_src sh
$ make
#+end_src

Before starting emacs, install =MSYS2=
to easily manage external dependencies. Install it to =C:\msys64=. Then
add =C:\msys64\mingw64\bin\= to the =PATH=.

* Update
To update and get the newest config, you just have to pull it from
github by calling:

#+begin_src sh
$ git pull origin master
#+end_src
