(setq dk/user-file-version {VERSION})
(setq user-full-name "{NAME}")
(setq user-mail-address "{EMAIL}")
(setq dk/user-system-base-path "~/")
(setq dk/org-roam-dir "~/Notes/")
(setq dk/use-40-percent-keyboard {KEYBOARD})

(defun dk/user-file-setup ()
  (dk/use-module! 'custom-search)
  (dk/use-module! 'custom-theme)
  (dk/use-module! 'custom-helm)
  ;; (dk/use-module! 'custom-ivy)
  (dk/use-module! 'text-org-mode)
  (dk/use-module! 'text-org-spell)
  (dk/use-module! 'text-org-roam)
  (dk/use-module! 'programming-base)
  (dk/use-module! 'programming-rust)
  (dk/use-module! 'programming-elisp)
  (dk/use-module! 'programming-python)
  (dk/use-module! 'programming-haskell)

  (dk/theme! 'humanoid-dark))

(defun dk/user-file-custom ())

