(setq user-full-name "{NAME}")
(setq user-mail-address "{EMAIL}")
(setq dk/user-system-base-path "~/")
(setq dk/org-roam-dir "~/Notes/")
(setq dk/use-40-percent-keyboard {KEYBOARD})

(dk/customize! 'custom-search)
(dk/customize! 'custom-funcs)
(dk/customize! 'custom-theme)
(dk/customize! 'custom-helm)
(dk/customize! 'text-org-mode)
(dk/customize! 'text-org-spell)
(dk/customize! 'text-org-roam)
(dk/customize! 'programming-base)
(dk/customize! 'programming-rust)
(dk/customize! 'programming-elisp)
(dk/customize! 'programming-python)
(dk/customize! 'programming-haskell)
