#+title: Custom functions in this config
#+author: Dominik Keller

* Non interactive functions
- =dk/log=: This macro expands to create the default logging scheme used
  in this config. The log is written to the =*Messages*= buffer. The
  first argument is a quoted symbol, that describes the severity of
  the log message. The available options are ='info=, ='warning= and
  ='error=. The rest are strings that will be concatenated.
- =dk/check-and-load-portable-file=: This function loads a file with
  definitions to start this config on a portable emacs installation.
  This function only loads the file if the environemnt variable
  =PORTABLE= is set to =1=. The file that is loaded is defined in the
  =dk/portable-definitions-file= variable. Per default, it also requires
  the =HOME= variable to be set to a location on the portable drive. It
  is recommended to write a startup script, that sets the environment
  variables.
- =dk/check-system=: This function checks what system is used and saves
  the custom system variables to =t=. Currently only =Windows= and
  =GNU/Linux= are supported.
- =dk/load-config=: This is the entry function for the config. Up until
  this point, there were just declarations to set the correct
  environment to call the main function. The function gets the files
  from =dk/config-file-list=. It iterates over them and =requires= them.
  All files that are required must be in a directory, that is in the
  =load-path= list.
- =dk/set-config-variables=: This function writes the file with the
  definitions for setting installation specific variables.
- =dk/check-ends-as-dir=: This is a helper function for
  =dk/set-config-variables=.
- =dk/check-config-variables=: This function checks if the installation
  specific file exists. If it exists, it will be loaded. Otherwise,
  the prompt for setting them will be called.
- =dk/bool-to-string=: Convert a bool to a string.
- =dk/delete-unused-config-dirs=: This is a hack to delete folders that
  are created at startup. It takes a list with names of directories
  that should be deleted. This should be obsolete at some point.
- =dk/count-loadable-files=: Count the number of files in
  =dk/config-file-list=. If the =cdr= is nil, the counter won't be
  incremented.
- =dk/locate-config-error=: This hacky function tries to pinpoint, where
  the config init stopped. The index is the number of loaded files
  from =dk/config-file-list=.
- =display-startup-echo-area-message=: Redefinition of a function that
  is defined by emacs.
- =org-export-output-file-name=: An advice to export the file to a
  subdir relative to the to-be exported file. 
- =dk/org-id-link-export=: a function that is used to extract the text
  out of the org-id-links.
- =dk/40-percent-keyboard-mode=: A minor mode, that redefines certain
  keybindings to make Emacs usable on 40% keyboards.
- =dk/search-open-file=: This function opens the config file.
- =dk/search-extract-files=: This function extracts the files from the
  =dk/config-file-list=.
- =dk/search-check-prefix=: Check if the name if the file must be
  prepended with the subdir prefix, because certain files are not in
  the subdir.
- =dk/load-theme=: This function takes a theme name and loads the theme.

* User callable interactive functions
- =dk/reload-config=: This function is to reload the config. This may
  lead to undesired behaviour, because only a restart of emacs can
  completely reload the config.
- =dk/trackpad-mode=: Enable the =good-scroll-mode=. This is an alias.
- =dk/reset-config-variables=: If this function is called, the custom
  file will be deleted and the prompt for setting the new paths will
  be called.
- =dk/set-default-coding-system=: Set the default coding system, that is
  defined in the =dk/default-coding-system= variable. This errors if the
  variable is nil. It is unlikely that this must be called, because it
  will be set at startup.
- =dk/greet=: Write a nice welcome message to the minibuffer. If the
  argument is =t=, it will not message, but return it. By default it is
  the title on the dashboard.
- =dk/kill-word-at-point=: Delete the word, where the point is pointing
  at.
- =dk/delete-window=: A custom function that wraps the function
  =delete-window= and =balance-windows= to have all windows at the same
  size after deleting one.
- =dk/play-a-game=: If the param is given and a symbol, it will call
  that function. Otherwise, it will pick a random game, that is
  defined in the constant =dk/games=.
- =dk/enable-centering=: Wrapper around =olivetti-mode= to enable it.
- =dk/disable-centering=: Wrapper around =olivetti-mode= to disable it.
- =dk/package-update-packages=: Update all packages that are installed
  by the different providers.
- =dk/config-version=: Get the string of the config. If not-print is =t=,
  the config won't be logged. If only-version is =t=, the sentence
  around the version string is not returned.
- =dk/explorer=: Open the file explorer. Under windows, =explorer= is
  called. Under GNU/Linux, =xdg-open= is called. It will allways use the
  path of the current buffer.
- =dk/display-startup-message=: This is an interactive wrapper around
  =display-startup-echo-area-message=.
- =dk/check-external-deps=: Interactivey checks if the external
  dependencies defined in =dk/system-dependencies= are available.
- =dk/search-config-file=: This function uses helm to select a file from
  =dk/config-file-list= and then call a function to open the specified
  file.
- =dk/load-light-theme=: This function loads the theme specified in
  =dk/light-theme=.
- =dk/load-dark-theme=: This function loads the theme specified in
  =dk/dark-theme=.
